### PR TITLE
fix: publish automation errors

### PR DESCRIPTION
**Pull request by jajugoguma**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- Add 'latest' from CDN to bundle upload path.
- Change wrapper publish automation to local works.
  - If it is automated through a GitHub action, it does not work properly due to the protection policy of the master branch.
  - Changed to local task because the protection of the branch is prioritized over the convenience of automation.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Review by jwlee1108 — APPROVED** [review]
리뷰 완료합니다.

**Review by lja1018 — APPROVED** [review]
리뷰완료합니다.

**Review by adhrinae — APPROVED** [review]
리뷰 완료합니다.

**Review by js87zz — APPROVED** [review]
리뷰 완료!

**Pull request merged**
