### PR TITLE
fix: bug that initialize filter date format

### PR DESCRIPTION
**Pull request by ryum91**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description
Changed filter date format.
But, datepicker close and reopen the format is initialized.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by jung-han** [comment]
Can one of the admins verify this patch?

**Comment by jung-han** [comment]
@ryum91 저장소가 모노레포 형태로 변경이 되어 괜찮으시다면 수정사항을 다시 반영해주시면 감사하겠습니다.

**Comment by ryum91** [comment]
@jung-han 최신 버전 merge 하였습니다~

**Comment by js87zz** [comment]
@ryum91 
소스 확인하였고 rebase로 master 브랜치 최신본 반영해주시면 바로 머지하겠습니다~!
감사합니다 :)

**Comment by js87zz** [comment]
ok to test

**Pull request merged**
